apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gateway.yaml
- scraper.yaml
- translate.yaml
images:
- name: asia-southeast1-docker.pkg.dev/optimal-pursuit-410406/powtain/open-im-server
  newTag: newVersion
