apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-rpc-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-rpc-server
  template:
    metadata:
      labels:
        app: auth-rpc-server
    spec:
      containers:
        - name: auth-rpc-server-container
          image: asia-southeast1-docker.pkg.dev/optimal-pursuit-410406/powtain/open-im-server:0d5ee3c456025afe499484cf2c1fb1f3cebc0493
          command: ["openim-rpc-auth", "-c", "/config"]
          imagePullPolicy: Never
          env:
            - name: CONFIG_PATH
              value: "/config"
            - name: IMENV_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: openim-redis-secret
                  key: redis-password
          volumeMounts:
            - name: openim-config
              mountPath: "/config"
              readOnly: true
          ports:
            - containerPort: 10200
            - containerPort: 12200
      volumes:
        - name: openim-config
          configMap:
            name: openim-config
