apiVersion: apps/v1
kind: Deployment
metadata:
  name: msg-rpc-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: msg-rpc-server
  template:
    metadata:
      labels:
        app: msg-rpc-server
    spec:
      containers:
        - name: msg-rpc-server-container
          image: asia-southeast1-docker.pkg.dev/optimal-pursuit-410406/powtain/open-im-server:0d5ee3c456025afe499484cf2c1fb1f3cebc0493
          command: ["openim-rpc-msg", "-c", "/config"]
          env:
            - name: CONFIG_PATH
              value: "/config"
            - name: IMENV_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: openim-redis-secret
                  key: redis-password
            - name: IMENV_MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: openim-mongo-secret
                  key: mongo_openim_username
            - name: IMENV_MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: openim-mongo-secret
                  key: mongo_openim_password
            - name: IMENV_KAFKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: openim-kafka-secret
                  key: kafka-password
          volumeMounts:
            - name: openim-config
              mountPath: "/config"
              readOnly: true
          ports:
            - containerPort: 10280
            - containerPort: 12280
      volumes:
        - name: openim-config
          configMap:
            name: openim-config
