name: Build and release services Images

on:
  push:
    branches:
      - main
  release:
    types: [published]

env:
  PROJECT_ID: optimal-pursuit-410406
  REGION: asia-southeast1
  GAR_PREFIX: asia-southeast1-docker.pkg.dev/optimal-pursuit-410406/powtain
  VERSION: "v3.8.3"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: "Docker auth"
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract metadata for Docker (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          tags: |
            type=ref,event=tag
            type=schedule
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern=v{{version}}
            # type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern=release-{{raw}}
            type=sha
            type=raw,value=${{ github.event.inputs.tag }}

      - name: Build and push Docker images
        run: |
          docker build . --tag ${{ env.GAR_PREFIX }}/open-im-server:${{ github.sha }}
          docker push ${{ env.GAR_PREFIX }}/open-im-server:${{ github.sha }}
          
