---
name: 'prod'

on:
  release:
    types: [published]

env:
  PROJECT_ID: optimal-pursuit-410406
  REGION: asia-southeast1
  GAR_LOCATION: asia-southeast1-docker.pkg.dev/optimal-pursuit-410406/powtain/open-im-server

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Cloning repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: Kubernetes set context
        uses: Azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.LIN_KUBE_CONF }}

        # Set up kustomize
        # TODO(dong): The cd here is ugly, but kustomize don't support edit
        # with different working directory so far.
      - name: Set up deploy env Kustomize
        run: |-
          cd deployments/deploy
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize

      - name: Deploy Linode Prod
        run: |-
          cd deployments/deploy
          ./kustomize edit set image ${{ env.GAR_LOCATION }}=:${{ github.sha }}
          kubectl apply -n prod -k .
